CREATE TABLE `pva-mvp-wip.property` (
  `property_id` uuid,
  `parcel_id` character varying(255),
  `lightbox_id` integer,
  `createdby` character varying(255),
  `timestamp` timestamp with time zone,
  `name` character varying(255),
  `appraisalusage` character varying(255),
  `readyforuse` boolean,
  `propertymajortype` character varying(255),
  `propertytype` character varying(255),
  `propertysubtype` character varying(255),
  `owner` text,
  `address` character varying(255),
  `city` character varying(255),
  `county` character varying(255),
  `state` character varying(255),
  `zip` character varying(255),
  `country` character varying(255),
  `lat` numeric,
  `lng` numeric,
  `parcelverificationdata` text,
  `isgroundlease` boolean,
  `market` character varying(255),
  `submarket` character varying(255),
  `townshiprange` text,
  `municipality` text,
  `cbsa_name` character varying(255),
  `cbsa_id` integer,
  `msa` text,
  `censusblock` text,
  `censustract` text,
  `neighborhood` text,
  `northboundary` character varying(255),
  `southboundary` character varying(255),
  `eastboundary` character varying(255),
  `westboundary` character varying(255),
  `neighborhoodcomments` character varying(255),
  `locationdescription` character varying(255),
  `opportunityzone` text,
  `schooldistrict` text,
  `districtspending` numeric,
  `districturl` text,
  `studentteacherratio` numeric,
  `enrollment` numeric,
  `parcelcomments` character varying(255),
  `appraisalfile` text,
  `otherdbrefs` text,
  `supportingfiles` text,
  `far` numeric,
  PRIMARY KEY (`property_id`),
  KEY `AK` (`parcel_id`)
);

CREATE TABLE `pva-mvp-wip.project` (
  `project_id` uuid,
  `project_name` character varying(255),
  `client_name` character varying(255),
  `status` character varying(50),
  `created_by_user_id` uuid,
  `created_at` timestamp with time zone,
  PRIMARY KEY (`project_id`)
);

CREATE TABLE `pva-mvp-wip.property` (
  `property_id` uuid,
  `parcel_id` character varying(255),
  `id` integer,
  `createdby` character varying(255),
  `timestamp` timestamp with time zone,
  `name` character varying(255),
  `appraisalusage` character varying(255),
  `readyforuse` boolean,
  `propertymajortype` character varying(255),
  `propertytype` character varying(255),
  `propertysubtype` character varying(255),
  `owner` text,
  `address` character varying(255),
  `city` character varying(255),
  `county` character varying(255),
  `state` character varying(255),
  `zip` character varying(255),
  `country` character varying(255),
  `lat` numeric,
  `lng` numeric,
  `parcelverificationdata` text,
  `isgroundlease` boolean,
  `market` character varying(255),
  `submarket` character varying(255),
  `townshiprange` text,
  `municipality` text,
  `cbsa_name` character varying(255),
  `cbsa_id` integer,
  `msa` text,
  `censusblock` text,
  `censustract` text,
  `neighborhood` text,
  `northboundary` character varying(255),
  `southboundary` character varying(255),
  `eastboundary` character varying(255),
  `westboundary` character varying(255),
  `neighborhoodcomments` character varying(255),
  `locationdescription` character varying(255),
  `opportunityzone` text,
  `schooldistrict` text,
  `districtspending` numeric,
  `districturl` text,
  `studentteacherratio` numeric,
  `enrollment` numeric,
  `parcelcomments` character varying(255),
  `appraisalfile` text,
  `otherdbrefs` text,
  `supportingfiles` text,
  `far` numeric,
  PRIMARY KEY (`property_id`),
  KEY `AK` (`parcel_id`)
);

CREATE TABLE `pva-mvp-wip.time_log` (
  `time_log_id` uuid,
  `user_id` uuid,
  `project_id` uuid,
  `property_id` uuid,
  `session_start` timestamp with time zone,
  `session_end` timestamp with time zone,
  `duration_seconds` integer,
  `activity_description` text,
  PRIMARY KEY (`time_log_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`),
  FOREIGN KEY (`project_id`)
      REFERENCES `pva-mvp-wip.project`(`project_id`)
);

CREATE TABLE `pva-mvp-wip.site` (
  `site_id` uuid,
  `property_id` uuid,
  `numberofparcels` integer,
  `landuse` text,
  `acres` numeric,
  `landsf` numeric,
  `buildablesf` integer,
  `landhectares` numeric,
  `landsquaremeters` numeric,
  `allowablefloorareasf` integer,
  `allowableunits` integer,
  `proposedsf` integer,
  `proposedunits` integer,
  `landunits` integer,
  `landunittype` text,
  `landunitapprovedorzoned` character varying(255),
  `roadfrontage` character varying(255),
  `primaryfrontagelf` numeric,
  `primaryfrontagest` text,
  `secondaryfrontagelf` numeric,
  `secondaryfrontagest` text,
  `tertiaryfrontagelf` numeric,
  `tertiaryfrontagest` character varying(255),
  `dimensions` text,
  `waterfrontage` integer,
  `effectivewaterfrontage` integer,
  `depth` character varying(255),
  `access` text,
  `views` text,
  `visibility` text,
  `shape` text,
  `topography` text,
  `corner` text,
  `utilities` text,
  `allutilities` boolean,
  `floodzone` text,
  `floodmappanel` character varying(255),
  `femamapdate` character varying(255),
  `withinfloodplainname` character varying(255),
  `areainfloodzone` numeric,
  `earthquakehazardrisk` character varying(255),
  `earthquakezonecomments` character varying(255),
  `encumbranceoreasement` text,
  `environmentalissues` text,
  `drainage` text,
  `railservice` character varying(255),
  `demographicssurveydate` timestamp with time zone,
  `medianhomevalue` numeric,
  `medianhouseholdincome` numeric,
  `trafficsurveydate` timestamp with time zone,
  `trafficcount` integer,
  `secondarytrafficcount` integer,
  `tertiarytrafficcount` integer,
  `soiltype` text,
  `productivityindex` numeric,
  `tillableacres` numeric,
  `percenttillable` numeric,
  `wetlandstype` text,
  `wetlandacres` numeric,
  `percentwetlands` numeric,
  `woodlandacres` numeric,
  `otheracres` numeric,
  `wasteacres` numeric,
  `homesiteacres` numeric,
  `sitecomments` character varying(255),
  PRIMARY KEY (`site_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip.improvement` (
  `improvement_id` uuid,
  `property_id` uuid,
  `buildingdescription` character varying(255),
  `noofbuildings` integer,
  `constructionclass` character varying(255),
  `buildingclass` character varying(255),
  `perimeter` numeric,
  `sourceforsfarea` character varying(255),
  `noofmultifamilyrooms` numeric,
  `noofmultifamilybedrooms` numeric,
  `noofmfbathrooms` numeric,
  `multifamilyamenities` character varying(255),
  `usablearea` numeric,
  `loadfactor` numeric,
  `noofunits` integer,
  `gbatotal` numeric,
  `ratotal` numeric,
  `landtobuildingratio` numeric,
  `surfaceparkingspaces` integer,
  `coveredparkingspaces` integer,
  `garageparkingspaces` integer,
  `parking` integer,
  `parkingratiounit` numeric,
  `parkingratiogba` numeric,
  `parkingratiora` numeric,
  `noofstories` integer,
  `noofrooms` numeric,
  `noofseats` integer,
  `noofbeds` integer,
  `noofbedrooms` numeric,
  `noofbathrooms` numeric,
  `noofhalfbaths` integer,
  `noofspaces` integer,
  `noofbays` integer,
  `noofgolfholes` integer,
  `adr` numeric,
  `lhoccupancy` numeric,
  `revpar` numeric,
  `productsegment` character varying(255),
  `hotelflag` character varying(255),
  `designappeal` character varying(255),
  `condition` character varying(255),
  `construction` character varying(255),
  `quality` character varying(255),
  `landscaping` character varying(255),
  `parkingtype` character varying(255),
  `parkingadequacy` character varying(255),
  `parkingcondition` character varying(255),
  `parkingcomments` character varying(255),
  `deferredmaintance` character varying(255),
  `ffande` character varying(255),
  `yearbuilt` character varying(255),
  `yearbuiltnumeric` integer,
  `renovations` character varying(255),
  `proportionrenovated` numeric,
  `totaleconomiclife` integer,
  `effectiveage` integer,
  `remainingeconomiclife` numeric,
  `foundation` text,
  `exteriorwall` text,
  `basementuseandfinish` character varying(255),
  `basementsize` integer,
  `columnspacing` character varying(255),
  `ceilingheight` character varying(255),
  `roofcover` character varying(255),
  `rooftype` character varying(255),
  `nooftruckdoors` integer,
  `nooftruckdoorswithlevelers` integer,
  `craneways` boolean,
  `typicalbaydepth` integer,
  `clearheight` numeric,
  `cooling` character varying(255),
  `heating` character varying(255),
  `noofelevators` integer,
  `noofescalators` integer,
  `sprinklers` character varying(255),
  `residentialdesign` character varying(255),
  `residentialamenities` character varying(255),
  `fireplaceorwoodstove` character varying(255),
  `garage` character varying(255),
  `docks` character varying(255),
  `porchordeck` character varying(255),
  `ancillarybuildings` character varying(255),
  `tenantimprovements` character varying(255),
  `features` character varying(255),
  `amenities` character varying(255),
  `improvmentcomments` character varying(255),
  `gbatotalmeters` numeric,
  `ratotalmeters` numeric,
  `parcelid` character varying(255),
  `id` character varying(255),
  `improvement_subrecords_buildingdescription` character varying(255),
  `improvement_subrecords_constructionclass` character varying(255),
  `improvement_subrecords_buildingclass` character varying(255),
  `perimetersf` numeric,
  `improvement_subrecords_sourceforsfarea` character varying(255),
  `multifamilygba` numeric,
  `improvement_subrecords_multifamilyamenities` character varying(255),
  `officegba` numeric,
  `officera` numeric,
  `improvement_subrecords_usablearea` numeric,
  `improvement_subrecords_loadfactor` numeric,
  `retailgba` numeric,
  `retailgla` numeric,
  `industrialgba` numeric,
  `industrialra` numeric,
  `othergba` numeric,
  `otherra` numeric,
  `improvement_subrecords_noofunits` integer,
  `gba` numeric,
  `rentablearea` numeric,
  `improvement_subrecords_landtobuildingratio` numeric,
  `improvement_subrecords_surfaceparkingspaces` integer,
  `improvement_subrecords_coveredparkingspaces` integer,
  `improvement_subrecords_garageparkingspaces` integer,
  `improvement_subrecords_parking` integer,
  `improvement_subrecords_noofstories` integer,
  `improvement_subrecords_noofrooms` numeric,
  `improvement_subrecords_noofseats` integer,
  `improvement_subrecords_noofbeds` integer,
  `improvement_subrecords_noofbedrooms` numeric,
  `improvement_subrecords_noofbathrooms` numeric,
  `improvement_subrecords_noofhalfbaths` integer,
  `improvement_subrecords_noofspaces` integer,
  `improvement_subrecords_noofbays` integer,
  `improvement_subrecords_noofgolfholes` integer,
  `improvement_subrecords_designappeal` character varying(255),
  `conditionid` character varying(255),
  `improvement_subrecords_condition` character varying(255),
  `improvement_subrecords_construction` character varying(255),
  `qualityid` character varying(255),
  `improvement_subrecords_quality` character varying(255),
  `improvement_subrecords_landscaping` character varying(255),
  `parkingtypeid` character varying(255),
  `improvement_subrecords_parkingtype` character varying(255),
  `parkingadequacyid` character varying(255),
  `improvement_subrecords_parkingadequacy` character varying(255),
  `parkingconditionid` character varying(255),
  `improvement_subrecords_parkingcondition` character varying(255),
  `improvement_subrecords_parkingcomments` character varying(255),
  `improvement_subrecords_deferredmaintance` character varying(255),
  `improvement_subrecords_ffande` character varying(255),
  `improvement_subrecords_yearbuilt` character varying(255),
  `improvement_subrecords_renovations` character varying(255),
  `improvement_subrecords_proportionrenovated` numeric,
  `improvement_subrecords_totaleconomiclife` integer,
  `improvement_subrecords_effectiveage` integer,
  `improvement_subrecords_remainingeconomiclife` numeric,
  `foundationid` character varying(255),
  `improvement_subrecords_foundation` text,
  `exteriorwallid` character varying(255),
  `improvement_subrecords_exteriorwall` text,
  `improvement_subrecords_basementuseandfinish` character varying(255),
  `improvement_subrecords_basementsize` integer,
  `improvement_subrecords_columnspacing` character varying(255),
  `improvement_subrecords_ceilingheight` character varying(255),
  `roofcoverid` character varying(255),
  `improvement_subrecords_roofcover` character varying(255),
  `rooftypeid` character varying(255),
  `improvement_subrecords_rooftype` character varying(255),
  `improvement_subrecords_nooftruckdoors` integer,
  `improvement_subrecords_nooftruckdoorswithlevelers` integer,
  `improvement_subrecords_typicalbaydepth` integer,
  `improvement_subrecords_clearheight` numeric,
  `coolingid` character varying(255),
  `improvement_subrecords_cooling` character varying(255),
  `heatingid` character varying(255),
  `improvement_subrecords_heating` character varying(255),
  `improvement_subrecords_noofelevators` integer,
  `improvement_subrecords_noofescalators` integer,
  `sprinklersid` character varying(255),
  `improvement_subrecords_sprinklers` character varying(255),
  `improvement_subrecords_residentialdesign` character varying(255),
  `improvement_subrecords_residentialamenities` character varying(255),
  `improvement_subrecords_fireplaceorwoodstove` character varying(255),
  `improvement_subrecords_garage` character varying(255),
  `improvement_subrecords_docks` character varying(255),
  `improvement_subrecords_porchordeck` character varying(255),
  `improvement_subrecords_ancillarybuildings` character varying(255),
  `improvement_subrecords_tenantimprovements` character varying(255),
  `improvement_subrecords_gbatotalmeters` numeric,
  `improvement_subrecords_ratotalmeters` numeric,
  PRIMARY KEY (`improvement_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip.site_area_breakdown` (
  `site_area_id` uuid,
  `site_id` uuid,
  `area_category` character varying(50),
  `acres` numeric,
  `square_feet` numeric,
  PRIMARY KEY (`site_area_id`),
  FOREIGN KEY (`site_area_id`)
      REFERENCES `pva-mvp-wip.site`(`site_id`)
);

CREATE TABLE `pva-mvp-wip.improvement_use_mix` (
  `use_mix_id` uuid,
  `improvement_id` uuid,
  `use_type` character varying(50),
  `number_of_units` integer,
  `gross_building_area` numeric,
  `net_rentable_area` numeric,
  PRIMARY KEY (`use_mix_id`),
  FOREIGN KEY (`use_mix_id`)
      REFERENCES `pva-mvp-wip.improvement`(`improvement_id`)
);

CREATE TABLE `pva-mvp-wip.property_zoning` (
  `property_zoning_id` uuid,
  `property_id` uuid,
  `jurisdiction` text,
  `district` text,
  `zoningcode` text,
  `type` text,
  `summary` character varying(255),
  `zoneddensity` character varying(255),
  `permitteduses` character varying(255),
  `maxsitecoverage` text,
  `minimumlotarea` text,
  `setbackdistance` text,
  `sideyarddistance` text,
  `rearyarddistance` text,
  `maxbuildheight` character varying(255),
  `parkingrequirement` character varying(255),
  `ordinancedocument` character varying(255),
  `comments` character varying(255),
  `id` character varying(255),
  `zoningid` character varying(255),
  `authority` character varying(255),
  `zoning_subrecords_district` text,
  `zoning` text,
  `zoning_subrecords_type` text,
  `zoning_subrecords_summary` character varying(255),
  `zoning_subrecords_zoneddensity` character varying(255),
  `zoning_subrecords_permitteduses` character varying(255),
  `zoning_subrecords_maxsitecoverage` text,
  `minlotarea` text,
  `frontsetbackdistance` text,
  `zoning_subrecords_sideyarddistance` text,
  `backyarddistance` text,
  `zoning_subrecords_maxbuildheight` character varying(255),
  `zoning_subrecords_parkingrequirement` character varying(255),
  `zoning_subrecords_ordinancedocument` character varying(255),
  `zoning_subrecords_comments` character varying(255),
  PRIMARY KEY (`property_zoning_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip.project_property` (
  `project_property_id` uuid,
  `project_id` uuid,
  `property_id` uuid,
  `assigned_to_user_id` uuid,
  `added_at` timestamp with time zone,
  PRIMARY KEY (`project_property_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`),
  FOREIGN KEY (`project_id`)
      REFERENCES `pva-mvp-wip.project`(`project_id`)
);

CREATE TABLE `pva-mvp-wip.sale_comp` (
  `sale_comp_id` uuid,
  `property_id` uuid,
  `pgim` numeric,
  `egim` numeric,
  `caprate` numeric,
  `saledate` timestamp with time zone,
  `transactiontype` character varying(255),
  `id` integer,
  `activestatus` boolean,
  `isdeleted` boolean,
  `isexcel` boolean,
  `confidential` boolean,
  `priceactual` numeric,
  `ffandeadjustment` numeric,
  `excesslandadjustment` numeric,
  `businessvalueadjustment` numeric,
  `financingtermsadjustment` numeric,
  `conditionsofsaleadjustment` numeric,
  `expendituresaftersaleadjustment` numeric,
  `otheradjustment` numeric,
  `priceadjustment` numeric,
  `price` numeric,
  `pricepersf` numeric,
  `priceperra` numeric,
  `priceperunit` numeric,
  `priceperroom` numeric,
  `priceperbedroom` numeric,
  `priceperbed` numeric,
  `pricepermfroom` numeric,
  `pricepermfbedroom` numeric,
  `priceperlandsf` numeric,
  `priceperacre` numeric,
  `priceperlandunit` numeric,
  `priceperusableacre` numeric,
  `priceperbuildablesf` numeric,
  `priceperprimaryfrontage` numeric,
  `priceperfar` numeric,
  `priceperbay` numeric,
  `priceperspace` numeric,
  `pricepergbameters` numeric,
  `priceperrameters` numeric,
  `priceperlandsqm` numeric,
  `priceperlandhectares` numeric,
  `grantor` character varying(255),
  `grantee` character varying(255),
  `propertyrights` character varying(255),
  `financing` text,
  `conditionsofsale` text,
  `currentuse` text,
  `propertyincluded` character varying(255),
  `daysonmarket` text,
  `recordingdate` date,
  `bookpageorrefdoc` character varying(255),
  `lender` character varying(255),
  `buyertype` character varying(255),
  `proposeduse` text,
  `highestandbestuse` character varying(255),
  `verificationsource` character varying(255),
  `verificationphone` character varying(255),
  `verificationdate` date,
  `datasource` character varying(255),
  `salesupportingfiles` text,
  `legaldescription` character varying(255),
  `finishcondition` character varying(255),
  `appraisaldate` character varying(255),
  `appraisedvalue` numeric,
  `landvaluepersf` numeric,
  `landvalue` numeric,
  `improvementvalue` numeric,
  `improvementvaluepersf` numeric,
  `nim` numeric,
  `hotelroomrevmultiplier` numeric,
  `toscaprate` numeric,
  `tosegim` numeric,
  `tosnoi` numeric,
  `tosoccupancyrate` numeric,
  `tosvacancyrate` numeric,
  `tospriceperrsf` numeric,
  `tospriceperuseableacreland` numeric,
  `tospriceperuseablesfland` numeric,
  `tosnumberoftenants` integer,
  `tostenancytype` character varying(255),
  `tosweightedaverageleaseterm` numeric,
  `toseffectiveage` integer,
  `discountrate` numeric,
  `expensegrowthrate` numeric,
  `incomegrowthrate` numeric,
  `terminalcaprate` numeric,
  `holdingperiodyears` integer,
  `incomegrowth` character varying(255),
  `riskprofile` character varying(255),
  `originallistprice` numeric,
  `originallppercentdiff` numeric,
  `currentlistprice` numeric,
  `currentlppercentdiff` numeric,
  `environmentalconcerns` character varying(255),
  `environmentalstatus` character varying(255),
  `environmentalremarks` character varying(255),
  `cleanupcosts` numeric,
  `typeofcontamination` character varying(255),
  `responsibleparty` character varying(255),
  `percentdiminutioninvalue` numeric,
  `diminutionsource` character varying(255),
  `percentstigma` numeric,
  `adjustmentcomments` character varying(255),
  `internalcomments` character varying(255),
  `salenotes` character varying(255),
  `salecomments` character varying(255),
  `priceperusablelandsf` numeric,
  PRIMARY KEY (`sale_comp_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip.commercial_survey` (
  `commercial_survey_id` uuid,
  `property_id` uuid,
  `id` character varying(255),
  `instancetype` character varying(255),
  `commleasesurveydate` timestamp with time zone,
  `confidential` boolean,
  `commrentpersfmin` numeric,
  `commrentpersfmax` numeric,
  `rentpersfpermomin` numeric,
  `rentpersfpermomax` numeric,
  `commsizemin` integer,
  `commsizemax` integer,
  `commverificationsource` text,
  `commvacancy` numeric,
  `nooftenants` numeric,
  `sfleased` numeric,
  `anchors` character varying(255),
  `shadowanchors` character varying(255),
  `commleasecomments` character varying(255),
  `tenant` text,
  `commleasetype` text,
  `commleasenotes` text,
  `commleaseterms` text,
  `commrentconcessions` text,
  `rent_roll_summary_commleasenotes` text,
  `escalations` text,
  PRIMARY KEY (`commercial_survey_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip.lease_comp` (
  `lease_comp_id` uuid,
  `commercial_survey_id` uuid,
  `id` character varying(255),
  `tenant` character varying(255),
  `lessor` text,
  `leasetype` text,
  `typeoruseofspace` text,
  `leasetransactiontype` text,
  `suite` text,
  `floorlevel` text,
  `unitsf` numeric,
  `effectiverentsf` numeric,
  `effectiverentsfmo` numeric,
  `effrentperyear` numeric,
  `effrentpermo` numeric,
  `leasestartdate` date,
  `leaseexpiredate` date,
  `baserentsf` numeric,
  `baserentsfmo` numeric,
  `baserentperyear` numeric,
  `baserentpermo` numeric,
  `leaseterm` text,
  `concessions` text,
  `expensestop` character varying(255),
  `leasedate` timestamp with time zone,
  `expensereimbursements` character varying(255),
  `leasetenantimprovs` character varying(255),
  `options` character varying(255),
  `percentrent` numeric,
  `tenantcam` numeric,
  `escalations` text,
  `verificationdate` timestamp with time zone,
  `verificationsource` character varying(255),
  `commleasesurveydate` timestamp with time zone,
  `datasource` character varying(255),
  `comments` character varying(255),
  `sizem2` numeric,
  `rentperm2` numeric,
  `rentperm2permo` numeric,
  `rentpersfpermo` numeric,
  `percentofficeul` numeric,
  `anchortype` text,
  `coststofinish` numeric,
  `currentrentpermo` numeric,
  `finish` text,
  `freerentmonths` integer,
  `leaseconditions` text,
  `rentbasis` text,
  `rentincreased` numeric,
  `tenantparking` numeric,
  PRIMARY KEY (`lease_comp_id`),
  FOREIGN KEY (`commercial_survey_id`)
      REFERENCES `pva-mvp-wip.commercial_survey`(`commercial_survey_id`)
);

CREATE TABLE `pva-mvp-wip.rent_comp` (
  `rent_comp_id` uuid,
  `property_id` uuid,
  `id` character varying(255),
  `mfleasesurveydate` timestamp with time zone,
  `mfsourcenotes` character varying(255),
  `instancetype` character varying(255),
  `managementcompany` text,
  `mfsurveyedunitcounttotal` integer,
  `mfvacantunitscount` integer,
  `vacancyrate` numeric,
  `mfoccupancy` numeric,
  `utilitiespaidbyowner` text,
  `mfrenttype` text,
  `mfrentconcessions` text,
  `mfcarportfeemonthly` numeric,
  `projectstyle` text,
  `mfgaragefeemonthly` numeric,
  `storagefee` numeric,
  `mfrentpermomin` numeric,
  `mfrentpermomax` numeric,
  `mfrentpersfmin` numeric,
  `mfrentpersfmax` numeric,
  `mfrentpersfpermomin` numeric,
  `mfrentpersfpermomax` numeric,
  `mfsizesfmin` integer,
  `mfsizesfmax` integer,
  `mfbrmin` numeric,
  `mfbrmax` numeric,
  `mftotalrentpermonth` numeric,
  `mftotalannualrent` numeric,
  `avgmfunitsize` numeric,
  `mfweightedavgrentperunit` numeric,
  `mfweightedavgrentpersfpermo` numeric,
  `mfweightedavgrentpersfperyear` numeric,
  `totalmarketrent` numeric,
  `projectamenities` character varying(255),
  `mfamenities` character varying(255),
  `mfleasecomments` character varying(255),
  `shpayormedicaidpercentage` numeric,
  `shpayormedicarepercentage` numeric,
  `shpayorvapercentage` numeric,
  `shpayorprivatepaypercentage` numeric,
  `shpayorotherpercentage` numeric,
  `shalunitcount` integer,
  `shaloccupancypercentage` numeric,
  `shalentryfee` numeric,
  `shalcommunityfee` numeric,
  `shalsecondpersonfeemonthly` numeric,
  `shilunitcount` integer,
  `shiloccupancypercentage` numeric,
  `shilentryfee` numeric,
  `shilcommunityfee` numeric,
  `shilsecondpersonfeemonthly` numeric,
  `shmcunitcount` integer,
  `shmcoccupancypercentage` numeric,
  `shmcentryfee` numeric,
  `shmccommunityfee` numeric,
  `shmcsecondpersonfeemonthly` numeric,
  `shsnunitcount` integer,
  `shsnoccupancypercentage` numeric,
  `shsnentryfee` numeric,
  `shsncommunityfee` numeric,
  `shsnsecondpersonfeemonthly` numeric,
  `shotherunitcount` integer,
  `shotheroccupancypercentage` numeric,
  `shotherentryfee` numeric,
  `shothercommunityfee` numeric,
  `shothersecondpersonfeemonthly` numeric,
  `shcaretypecomments` character varying(255),
  `mfleasenotes` text,
  PRIMARY KEY (`rent_comp_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip.unit_mix` (
  `unit_mix_id` uuid,
  `rent_comp_id` uuid,
  `category` text,
  `unittype` text,
  `unitcount` integer,
  `vacantunits` integer,
  `unitsf` numeric,
  `floor` character varying(255),
  `rooms` integer,
  `bedrooms` numeric,
  `baths` numeric,
  `beds` integer,
  `rentpermo` numeric,
  `annualrentpersf` numeric,
  `rentpersfpermo` numeric,
  `marketrentmo` numeric,
  `marketrentsf` numeric,
  `dailyrateperunit` numeric,
  `sizem2` numeric,
  `rentperm2` numeric,
  `lastrentincrease` character varying(255),
  `rentincreasepercent` numeric,
  `leasestart` character varying(255),
  `leaseexpiration` character varying(255),
  `communityfeemin` numeric,
  `communityfeemax` numeric,
  `sfsizemin` numeric,
  `sfsizemax` numeric,
  `dailyrateperunitmin` numeric,
  `dailyrateperunitmax` numeric,
  `entryfeemin` numeric,
  `entryfeemax` numeric,
  `contractrentmin` numeric,
  `contractrentmax` numeric,
  `marketrentmin` numeric,
  `marketrentmax` numeric,
  `unitheight` numeric,
  `unitwidth` numeric,
  `unitdepth` numeric,
  `incometarget` numeric,
  `maxgrosslihtcrestrictedrent` numeric,
  `lhtc` character varying(255),
  `utilityallowance` numeric,
  `occupancytype` text,
  `affordabilitystatus` text,
  `tenantprofile` text,
  `monthlyordailyrent` text,
  PRIMARY KEY (`unit_mix_id`),
  FOREIGN KEY (`rent_comp_id`)
      REFERENCES `pva-mvp-wip.rent_comp`(`rent_comp_id`)
);

CREATE TABLE `pva-mvp-wip.property_merge_audit_log` (
  `audit_log_id` uuid,
  `property_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip.property_source_attribution` (
  `attribution_id` uuid,
  `property_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `pva-mvp-wip.property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip.sale_comp_merge_audit_log` (
  `audit_log_id` uuid,
  `sale_comp_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`)
);

CREATE TABLE `pva-mvp-wip.sale_comp_source_attribution` (
  `attribution_id` uuid,
  `sale_comp_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`sale_comp_id`)
      REFERENCES `pva-mvp-wip.sale_comp`(`sale_comp_id`)
);

CREATE TABLE `pva-mvp-wip.rent_comp_merge_audit_log` (
  `audit_log_id` uuid,
  `rent_comp_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`),
  FOREIGN KEY (`rent_comp_id`)
      REFERENCES `pva-mvp-wip.rent_comp`(`rent_comp_id`)
);

CREATE TABLE `pva-mvp-wip.rent_comp_source_attribution` (
  `attribution_id` uuid,
  `rent_comp_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`rent_comp_id`)
      REFERENCES `pva-mvp-wip.rent_comp`(`rent_comp_id`)
);

CREATE TABLE `pva-mvp-wip.lease_comp_merge_audit_log` (
  `audit_log_id` uuid,
  `lease_comp_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`),
  FOREIGN KEY (`lease_comp_id`)
      REFERENCES `pva-mvp-wip.lease_comp`(`lease_comp_id`)
);

CREATE TABLE `pva-mvp-wip.lease_comp_source_attribution` (
  `attribution_id` uuid,
  `lease_comp_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`lease_comp_id`)
      REFERENCES `pva-mvp-wip.lease_comp`(`lease_comp_id`)
);

CREATE TABLE `pva-mvp-wip.commercial_survey_merge_audit_log` (
  `audit_log_id` uuid,
  `commercial_survey_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`)
);

CREATE TABLE `pva-mvp-wip.commercial_survey_source_attribution` (
  `attribution_id` uuid,
  `commercial_survey_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`commercial_survey_id`)
      REFERENCES `pva-mvp-wip.commercial_survey`(`commercial_survey_id`)
);

CREATE TABLE `pva-mvp-wip.unit_mix_merge_audit_log` (
  `audit_log_id` uuid,
  `unit_mix_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`),
  FOREIGN KEY (`unit_mix_id`)
      REFERENCES `pva-mvp-wip.unit_mix`(`unit_mix_id`)
);

CREATE TABLE `pva-mvp-wip.unit_mix_source_attribution` (
  `attribution_id` uuid,
  `unit_mix_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`unit_mix_id`)
      REFERENCES `pva-mvp-wip.unit_mix`(`unit_mix_id`)
);

CREATE TABLE `pva-mvp-wip.improvement_merge_audit_log` (
  `audit_log_id` uuid,
  `improvement_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`),
  FOREIGN KEY (`improvement_id`)
      REFERENCES `pva-mvp-wip.improvement`(`improvement_id`)
);

CREATE TABLE `pva-mvp-wip.improvement_source_attribution` (
  `attribution_id` uuid,
  `improvement_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`improvement_id`)
      REFERENCES `pva-mvp-wip.improvement`(`improvement_id`)
);

CREATE TABLE `pva-mvp-wip.site_merge_audit_log` (
  `audit_log_id` uuid,
  `site_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`),
  FOREIGN KEY (`site_id`)
      REFERENCES `pva-mvp-wip.site`(`site_id`)
);

CREATE TABLE `pva-mvp-wip.site_source_attribution` (
  `attribution_id` uuid,
  `site_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`site_id`)
      REFERENCES `pva-mvp-wip.site`(`site_id`)
);

CREATE TABLE `pva-mvp-wip.improvement_use_mix_merge_audit_log` (
  `audit_log_id` uuid,
  `use_mix_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`),
  FOREIGN KEY (`use_mix_id`)
      REFERENCES `pva-mvp-wip.improvement_use_mix`(`use_mix_id`)
);

CREATE TABLE `pva-mvp-wip.improvement_use_mix_source_attribution` (
  `attribution_id` uuid,
  `use_mix_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`use_mix_id`)
      REFERENCES `pva-mvp-wip.improvement_use_mix`(`use_mix_id`)
);

CREATE TABLE `pva-mvp-wip.property_zoning_merge_audit_log` (
  `audit_log_id` uuid,
  `property_zoning_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`),
  FOREIGN KEY (`property_zoning_id`)
      REFERENCES `pva-mvp-wip.property_zoning`(`property_zoning_id`)
);

CREATE TABLE `pva-mvp-wip.property_zoning_source_attribution` (
  `attribution_id` uuid,
  `property_zoning_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`property_zoning_id`)
      REFERENCES `pva-mvp-wip.property_zoning`(`property_zoning_id`)
);

CREATE TABLE `pva-mvp-wip.site_area_breakdown_merge_audit_log` (
  `audit_log_id` uuid,
  `site_area_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`),
  FOREIGN KEY (`site_area_id`)
      REFERENCES `pva-mvp-wip.site_area_breakdown`(`site_area_id`)
);

CREATE TABLE `pva-mvp-wip.site_area_breakdown_source_attribution` (
  `attribution_id` uuid,
  `site_area_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`site_area_id`)
      REFERENCES `pva-mvp-wip.site_area_breakdown`(`site_area_id`)
);

