CREATE TABLE `pva-mvp-wip-v2.property_type_ref` (
  `property_type_id` integer,
  `major_type` character varying(255),
  `property_type` character varying(255),
  `sub_type` character varying(255),
  `is_active` boolean,
  PRIMARY KEY (`property_type_id`)
);

CREATE TABLE `Geography` (
  `geography_id` uuid,
  `geo_type` character varying(50),
  `geo_name` character varying(255),
  `geo_code` character varying(50),
  `parent_geo_id` uuid,
  `lat_centroid` numeric,
  `lng_centroid` numeric,
  `north_boundary` character varying(255),
  `south_boundary` character varying(255),
  `east_boundary` character varying(255),
  `west_boundary` character varying(255),
  `boundary_comments` character varying(255),
  `opportunity_zone` boolean,
  `vacancy_rate` numeric,
  `avg_asking_rent_sf` numeric,
  `avg_cap_rate` numeric,
  `population` integer,
  `median_hh_income` numeric,
  `median_home_value` numeric,
  `created_at` timestamp with time zone,
  `updated_at` timestamp with time zone,
  `created_by_user_id` uuid,
  `updated_by_user_id` uuid,
  PRIMARY KEY (`geography_id`)
);

CREATE TABLE `Property` (
  `property_id` uuid,
  `parcel_id` character varying(255),
  `geography_id` uuid,
  `lightbox_id` integer,
  `lightbox_created_by` character varying(255),
  `lightbox_timestamp` timestamp with time zone,
  `name` character varying(255),
  `appraisal_usage` character varying(255),
  `ready_for_use` boolean,
  `property_type_id` integer,
  `owner` text,
  `address` character varying(255),
  `lat` numeric,
  `lng` numeric,
  `parcel_verification_data` text,
  `is_ground_lease` boolean,
  `parcel_comments` character varying(255),
  `appraisal_file` text,
  `other_db_refs` text,
  `supporting_files` text,
  `floor_area_ratio` numeric,
  `custom_fields` jsonb,
  `created_at` timestamp with time zone,
  `updated_at` timestamp with time zone,
  `created_by_user_id` uuid,
  `updated_by_user_id` uuid,
  PRIMARY KEY (`property_id`),
  FOREIGN KEY (`owner`)
      REFERENCES `pva-mvp-wip-v2.property_type_ref`(`property_type_id`),
  FOREIGN KEY (`geography_id`)
      REFERENCES `Geography`(`geography_id`),
  KEY `U` (`parcel_id`)
);

CREATE TABLE `pva-mvp-wip-v2.school_district` (
  `school_district_id` uuid,
  `geography_id` uuid,
  `district_name` text,
  `district_url` text,
  `enrollment` integer,
  `student_teacher_ratio` numeric,
  `per_pupil_spending` numeric,
  `created_at` timestamp with time zone,
  `updated_at` timestamp with time zone,
  PRIMARY KEY (`school_district_id`),
  FOREIGN KEY (`geography_id`)
      REFERENCES `Geography`(`geography_id`)
);

CREATE TABLE `pva-mvp-wip-v2.project` (
  `project_id` uuid,
  `project_name` character varying(255),
  `client_name` character varying(255),
  `status` character varying(50),
  `created_by_user_id` uuid,
  `created_at` timestamp with time zone,
  PRIMARY KEY (`project_id`)
);

CREATE TABLE `pva-mvp-wip-v2.project_property` (
  `project_property_id` uuid,
  `project_id` uuid,
  `property_id` uuid,
  `assigned_to_user_id` uuid,
  `added_at` timestamp with time zone,
  PRIMARY KEY (`project_property_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `Property`(`property_id`),
  FOREIGN KEY (`project_id`)
      REFERENCES `pva-mvp-wip-v2.project`(`project_id`)
);

CREATE TABLE `pva-mvp-wip-v2.site` (
  `site_id` uuid,
  `property_id` uuid,
  `number_of_parcels` integer,
  `land_use` text,
  `site_acres` numeric,
  `land_sf` numeric,
  `buildable_sf` integer,
  `land_hectares` numeric,
  `land_square_meters` numeric,
  `allowable_floor_area_sf` integer,
  `allowable_units` integer,
  `proposed_sf` integer,
  `proposed_units` integer,
  `land_units` integer,
  `land_unit_type` text,
  `land_unit_approved_or_zoned` character varying(255),
  `road_frontage` character varying(255),
  `primary_frontage_lf` numeric,
  `primary_frontage_st` text,
  `secondary_frontage_lf` numeric,
  `secondary_frontage_st` text,
  `tertiary_frontage_lf` numeric,
  `tertiary_frontage_st` text,
  `site_dimensions` text,
  `water_frontage` integer,
  `effective_water_frontage` integer,
  `depth` character varying(255),
  `access` text,
  `site_views` text,
  `site_visibility` text,
  `shape` text,
  `site_topography` text,
  `corner` text,
  `site_utilities` text,
  `all_utilities_to_site` boolean,
  `flood_zone` text,
  `flood_map_panel` character varying(255),
  `fema_map_date` character varying(255),
  `within_flood_plain` boolean,
  `area_in_flood_zone` numeric,
  `earthquake_hazard_risk` character varying(255),
  `earthquake_zone_comments` character varying(255),
  `encumbrance_or_easement` text,
  `environmental_issues` text,
  `site_drainage` text,
  `rail_service` character varying(255),
  `demographics_survey_date` timestamp with time zone,
  `median_home_value` numeric,
  `median_household_income` numeric,
  `traffic_survey_date` timestamp with time zone,
  `traffic_count` integer,
  `secondary_traffic_count` integer,
  `tertiary_traffic_count` integer,
  `soil_type` text,
  `productivity_index` numeric,
  `tillable_acres` numeric,
  `percent_tillable` numeric,
  `wetlands_type` text,
  `wetland_acres` numeric,
  `percent_wetlands` numeric,
  `woodland_acres` numeric,
  `other_acres` numeric,
  `waste_acres` numeric,
  `home_site_acres` numeric,
  `site_comments` character varying(255),
  `custom_fields` jsonb,
  `created_at` timestamp with time zone,
  `updated_at` timestamp with time zone,
  `created_by_user_id` uuid,
  `updated_by_user_id` uuid,
  PRIMARY KEY (`site_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `Property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip-v2.site_area_breakdown` (
  `site_area_id` uuid,
  `site_id` uuid,
  `area_category` character varying(50),
  `site_acres` numeric,
  `square_feet` numeric,
  PRIMARY KEY (`site_area_id`),
  FOREIGN KEY (`site_id`)
      REFERENCES `pva-mvp-wip-v2.site`(`site_id`)
);

CREATE TABLE `pva-mvp-wip-v2.improvement` (
  `improvement_id` uuid,
  `property_id` uuid,
  `building_description` character varying(255),
  `no_of_buildings` integer,
  `construction_class` character varying(255),
  `building_class` character varying(255),
  `perimeter` numeric,
  `source_for_sf_area` character varying(255),
  `no_of_multifamily_rooms` integer,
  `no_of_multifamily_bedrooms` integer,
  `no_of_mf_bathrooms` integer,
  `multifamily_amenities` character varying(255),
  `usable_area` numeric,
  `load_factor` numeric,
  `no_of_units` integer,
  `gba_total` numeric,
  `ra_total` numeric,
  `land_to_building_ratio` numeric,
  `surface_parking_spaces` integer,
  `covered_parking_spaces` integer,
  `garage_parking_spaces` integer,
  `parking` integer,
  `parking_ratio_unit` numeric,
  `parking_ratio_gba` numeric,
  `parking_ratio_ra` numeric,
  `no_of_stories` integer,
  `no_of_rooms` integer,
  `no_of_seats` integer,
  `no_of_beds` integer,
  `no_of_bedrooms` integer,
  `no_of_bathrooms` integer,
  `no_of_half_baths` integer,
  `no_of_spaces` integer,
  `no_of_bays` integer,
  `no_of_golf_holes` integer,
  `average_daily_rate` numeric,
  `lh_occupancy` numeric,
  `rev_par` numeric,
  `product_segment` character varying(255),
  `hotel_flag` character varying(255),
  `design_appeal` character varying(255),
  `building_condition` character varying(255),
  `construction_type` character varying(255),
  `building_quality` character varying(255),
  `site_landscaping` character varying(255),
  `parking_type` character varying(255),
  `parking_adequacy` character varying(255),
  `parking_condition` character varying(255),
  `parking_comments` character varying(255),
  `deferred_maintenance` character varying(255),
  `ff_and_e` character varying(255),
  `year_built` character varying(255),
  `year_built_numeric` integer,
  `renovations_description` character varying(255),
  `proportion_renovated` numeric,
  `total_economic_life` integer,
  `effective_age` integer,
  `remaining_economic_life` numeric,
  `foundation_type` text,
  `exterior_wall` text,
  `basement_use_and_finish` character varying(255),
  `basement_size` integer,
  `column_spacing` character varying(255),
  `ceiling_height` character varying(255),
  `roof_cover` character varying(255),
  `roof_type` character varying(255),
  `no_of_truck_doors` integer,
  `no_of_truck_doors_with_levelers` integer,
  `no_of_craneways` boolean,
  `typical_bay_depth` integer,
  `clear_height` numeric,
  `cooling_type` character varying(255),
  `heating_type` character varying(255),
  `no_of_elevators` integer,
  `no_of_escalators` integer,
  `sprinkler_type` character varying(255),
  `residential_design` character varying(255),
  `residential_amenities` character varying(255),
  `fireplace_or_woodstove` character varying(255),
  `garage_type` character varying(255),
  `no_of_docks` character varying(255),
  `porch_or_deck` character varying(255),
  `ancillary_buildings` character varying(255),
  `tenant_improvements` character varying(255),
  `building_features` character varying(255),
  `building_amenities` character varying(255),
  `improvement_comments` character varying(255),
  `gba_total_meters` numeric,
  `ra_total_meters` numeric,
  `parcel_id` character varying(255),
  `id` character varying(255),
  `perimeter_sf` numeric,
  `multifamily_gba` numeric,
  `office_gba` numeric,
  `office_ra` numeric,
  `retail_gba` numeric,
  `retail_gla` numeric,
  `industrial_gba` numeric,
  `industrial_ra` numeric,
  `other_gba` numeric,
  `other_ra` numeric,
  `gross_building_area` numeric,
  `rentable_area` numeric,
  `condition_id` character varying(255),
  `quality_id` character varying(255),
  `parking_type_id` character varying(255),
  `parking_adequacy_id` character varying(255),
  `parking_condition_id` character varying(255),
  `foundation_id` character varying(255),
  `exterior_wall_id` character varying(255),
  `roof_cover_id` character varying(255),
  `roof_type_id` character varying(255),
  `cooling_id` character varying(255),
  `heating_id` character varying(255),
  `sprinklers_id` character varying(255),
  `custom_fields` jsonb,
  `created_at` timestamp with time zone,
  `updated_at` timestamp with time zone,
  `created_by_user_id` uuid,
  `updated_by_user_id` uuid,
  PRIMARY KEY (`improvement_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `Property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip-v2.property_zoning` (
  `property_zoning_id` uuid,
  `property_id` uuid,
  `zoning_jurisdiction` text,
  `zoning_code` text,
  `minimum_lot_area` text,
  `setback_distance` text,
  `rear_yard_distance` text,
  `ordinance_document` character varying(255),
  `notes` character varying(255),
  `id` character varying(255),
  `zoning_id` character varying(255),
  `zoning_authority` character varying(255),
  `zoning_district` text,
  `zoning_designation` text,
  `zoning_type` text,
  `zoning_summary` character varying(255),
  `zoned_density` character varying(255),
  `permitted_uses` character varying(255),
  `max_site_coverage` text,
  `min_lot_area` text,
  `front_set_back_distance` text,
  `side_yard_distance` text,
  `back_yard_distance` text,
  `max_build_height` character varying(255),
  `parking_requirement` character varying(255),
  `ordinance_document_url` character varying(255),
  `zoning_notes` character varying(255),
  `created_at` timestamp with time zone,
  `updated_at` timestamp with time zone,
  `created_by_user_id` uuid,
  `updated_by_user_id` uuid,
  PRIMARY KEY (`property_zoning_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `Property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip-v2.time_log` (
  `time_log_id` uuid,
  `user_id` uuid,
  `project_id` uuid,
  `property_id` uuid,
  `session_start` timestamp with time zone,
  `session_end` timestamp with time zone,
  `duration_seconds` integer,
  `activity_description` text,
  PRIMARY KEY (`time_log_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `Property`(`property_id`),
  FOREIGN KEY (`project_id`)
      REFERENCES `pva-mvp-wip-v2.project`(`project_id`)
);

CREATE TABLE `pva-mvp-wip-v2.property_assessment` (
  `property_assessment_id` uuid,
  `property_id` uuid,
  `taxing_authority` character varying(255),
  `tax_id` character varying(255),
  `assessment_year` integer,
  `land_assessment` numeric,
  `improvement_assessment` numeric,
  `other_assessment` numeric,
  `total_assessment` numeric,
  `tax_rate` numeric,
  `base_taxes` numeric,
  `special_assessments` numeric,
  `total_taxes` numeric,
  `equalization_ratio` numeric,
  `implied_value` numeric,
  `custom_fields` jsonb,
  `created_at` timestamp with time zone,
  `updated_at` timestamp with time zone,
  `created_by_user_id` uuid,
  `updated_by_user_id` uuid,
  PRIMARY KEY (`property_assessment_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `Property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip-v2.sale_comp` (
  `sale_comp_id` uuid,
  `property_id` uuid,
  `potential_gross_income_multiplier` numeric,
  `effective_gross_income_multiplier` numeric,
  `cap_rate` numeric,
  `sale_date` timestamp with time zone,
  `transaction_type` character varying(255),
  `id` integer,
  `is_active` boolean,
  `is_deleted` boolean,
  `is_excel_entry` boolean,
  `is_confidential` boolean,
  `actual_price` numeric,
  `ff_and_e_adjustment` numeric,
  `excess_land_adjustment` numeric,
  `business_value_adjustment` numeric,
  `financing_terms_adjustment` numeric,
  `conditions_of_sale_adjustment` numeric,
  `expenditures_after_sale_adjustment` numeric,
  `other_adjustment` numeric,
  `price_adjustment` numeric,
  `sale_price` numeric,
  `price_per_sf` numeric,
  `price_per_ra` numeric,
  `price_per_unit` numeric,
  `price_per_room` numeric,
  `price_per_bedroom` numeric,
  `price_per_bed` numeric,
  `price_per_mf_room` numeric,
  `price_per_mf_bedroom` numeric,
  `price_per_land_sf` numeric,
  `price_per_acre` numeric,
  `price_per_land_unit` numeric,
  `price_per_usable_acre` numeric,
  `price_per_buildable_sf` numeric,
  `price_per_primary_frontage` numeric,
  `price_per_far` numeric,
  `price_per_bay` numeric,
  `price_per_space` numeric,
  `price_per_gba_meters` numeric,
  `price_per_ra_meters` numeric,
  `price_per_land_sqm` numeric,
  `price_per_land_hectares` numeric,
  `grantor_seller` character varying(255),
  `grantee_buyer` character varying(255),
  `property_rights` character varying(255),
  `financing_type` text,
  `conditions_of_sale` text,
  `current_use` text,
  `property_included` character varying(255),
  `days_on_market` text,
  `recording_date` date,
  `book_page_or_ref_doc` character varying(255),
  `lender_name` character varying(255),
  `buyer_type` character varying(255),
  `proposed_use` text,
  `highest_and_best_use` character varying(255),
  `verification_source` character varying(255),
  `verification_phone` character varying(255),
  `verificationdate` date,
  `data_source` character varying(255),
  `sale_supporting_files` text,
  `legal_description` character varying(255),
  `finish_condition` character varying(255),
  `appraisal_date` character varying(255),
  `appraised_value` numeric,
  `land_value_per_sf` numeric,
  `land_value` numeric,
  `improvement_value` numeric,
  `improvement_value_per_sf` numeric,
  `net_income_multiplier` numeric,
  `hotel_room_rev_multiplier` numeric,
  `tos_cap_rate` numeric,
  `tos_egim` numeric,
  `tos_noi` numeric,
  `tos_occupancy_rate` numeric,
  `tos_vacancy_rate` numeric,
  `tos_price_per_rsf` numeric,
  `tos_price_per_useable_acre_land` numeric,
  `tos_price_per_useable_sf_land` numeric,
  `tos_number_of_tenants` integer,
  `tos_tenancy_type` character varying(255),
  `tos_weighted_avg_lease_term` numeric,
  `tos_effective_age` integer,
  `discount_rate` numeric,
  `expense_growth_rate` numeric,
  `income_growth_rate` numeric,
  `terminal_cap_rate` numeric,
  `holding_period_years` integer,
  `income_growth` character varying(255),
  `risk_profile` character varying(255),
  `original_list_price` numeric,
  `original_lp_percent_diff` numeric,
  `current_list_price` numeric,
  `current_lp_percent_diff` numeric,
  `environmental_concerns` character varying(255),
  `environmental_status` character varying(255),
  `environmental_remarks` character varying(255),
  `clean_up_costs` numeric,
  `type_of_contamination` character varying(255),
  `responsible_party` character varying(255),
  `percent_diminution_in_value` numeric,
  `diminution_source` character varying(255),
  `percent_stigma` numeric,
  `adjustment_comments` character varying(255),
  `internal_comments` character varying(255),
  `sale_notes` character varying(255),
  `sale_comments` character varying(255),
  `price_per_usable_land_sf` numeric,
  `custom_fields` jsonb,
  `created_at` timestamp with time zone,
  `updated_at` timestamp with time zone,
  `created_by_user_id` uuid,
  `updated_by_user_id` uuid,
  PRIMARY KEY (`sale_comp_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `Property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip-v2.commercial_survey` (
  `commercial_survey_id` uuid,
  `property_id` uuid,
  `id` character varying(255),
  `instance_type` character varying(255),
  `comm_lease_survey_date` timestamp with time zone,
  `is_confidential` boolean,
  `comm_rent_per_sf_min` numeric,
  `comm_rent_per_sf_max` numeric,
  `rent_per_sf_per_mo_min` numeric,
  `rent_per_sf_per_mo_max` numeric,
  `comm_size_min` integer,
  `comm_size_max` integer,
  `comm_verification_source` text,
  `comm_vacancy_rate` numeric,
  `no_of_tenants` integer,
  `sf_leased` numeric,
  `anchor_tenants` character varying(255),
  `shadow_anchors` character varying(255),
  `comm_lease_comments` character varying(255),
  `tenant_name` text,
  `comm_lease_type` text,
  `comm_lease_notes` text,
  `comm_lease_terms` text,
  `comm_rent_concessions` text,
  `rent_roll_summary_commleasenotes` text,
  `rent_escalations` text,
  PRIMARY KEY (`commercial_survey_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `Property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip-v2.lease_comp` (
  `lease_comp_id` uuid,
  `commercial_survey_id` uuid,
  `id` character varying(255),
  `tenant_name` character varying(255),
  `lessor_name` text,
  `lease_type` text,
  `type_or_use_of_space` text,
  `lease_transaction_type` text,
  `suite_number` text,
  `floor_level` text,
  `unit_sf` numeric,
  `effective_rent_sf` numeric,
  `effective_rent_sf_mo` numeric,
  `eff_rent_per_year` numeric,
  `eff_rent_per_mo` numeric,
  `leasestartdate` date,
  `leaseexpiredate` date,
  `base_rent_sf` numeric,
  `base_rent_sf_mo` numeric,
  `base_rent_per_year` numeric,
  `base_rent_per_mo` numeric,
  `lease_term_months` text,
  `lease_concessions` text,
  `expense_stop` character varying(255),
  `lease_commencement_date` timestamp with time zone,
  `expense_reimbursements` character varying(255),
  `lease_tenant_improvs` character varying(255),
  `lease_options` character varying(255),
  `percent_rent` numeric,
  `tenant_cam` numeric,
  `rent_escalations` text,
  `verification_date` timestamp with time zone,
  `verification_source` character varying(255),
  `comm_lease_survey_date` timestamp with time zone,
  `data_source` character varying(255),
  `notes` character varying(255),
  `size_sq_meters` numeric,
  `rent_per_sq_meter` numeric,
  `rent_per_sq_meter_per_mo` numeric,
  `rent_per_sf_per_mo` numeric,
  `percent_office_ul` numeric,
  `anchor_type` text,
  `costs_to_finish` numeric,
  `current_rent_per_mo` numeric,
  `space_finish` text,
  `free_rent_months` integer,
  `lease_conditions` text,
  `rent_basis` text,
  `rent_last_increased` numeric,
  `tenant_parking` numeric,
  `custom_fields` jsonb,
  `created_at` timestamp with time zone,
  `updated_at` timestamp with time zone,
  `created_by_user_id` uuid,
  `updated_by_user_id` uuid,
  PRIMARY KEY (`lease_comp_id`),
  FOREIGN KEY (`commercial_survey_id`)
      REFERENCES `pva-mvp-wip-v2.commercial_survey`(`commercial_survey_id`)
);

CREATE TABLE `pva-mvp-wip-v2.rent_comp` (
  `rent_comp_id` uuid,
  `property_id` uuid,
  `id` character varying(255),
  `mf_lease_survey_date` timestamp with time zone,
  `mf_source_notes` character varying(255),
  `instance_type` character varying(255),
  `management_company` text,
  `mf_surveyed_unit_count_total` integer,
  `mf_vacant_units_count` integer,
  `vacancy_rate` numeric,
  `mf_occupancy` numeric,
  `utilities_paid_by_owner` text,
  `mf_rent_type` text,
  `mf_rent_concessions` text,
  `mf_carport_fee_monthly` numeric,
  `project_style` text,
  `mf_garage_fee_monthly` numeric,
  `storage_fee` numeric,
  `mf_rent_per_mo_min` numeric,
  `mf_rent_per_mo_max` numeric,
  `mf_rent_per_sf_min` numeric,
  `mf_rent_per_sf_max` numeric,
  `mf_rent_per_sf_per_mo_min` numeric,
  `mf_rent_per_sf_per_mo_max` numeric,
  `mf_size_sf_min` integer,
  `mf_size_sf_max` integer,
  `mf_br_min` numeric,
  `mf_br_max` numeric,
  `mf_total_rent_per_month` numeric,
  `mf_total_annual_rent` numeric,
  `avg_mf_unit_size` numeric,
  `mf_weighted_avg_rent_per_unit` numeric,
  `mf_weighted_avg_rent_per_sf_per_mo` numeric,
  `mf_weighted_avg_rent_per_sf_per_year` numeric,
  `total_market_rent` numeric,
  `project_amenities` character varying(255),
  `mf_unit_amenities` character varying(255),
  `mf_lease_comments` character varying(255),
  `care_type_comments` character varying(255),
  `mf_lease_notes` text,
  `custom_fields` jsonb,
  `created_at` timestamp with time zone,
  `updated_at` timestamp with time zone,
  `created_by_user_id` uuid,
  `updated_by_user_id` uuid,
  PRIMARY KEY (`rent_comp_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `Property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip-v2.unit_mix` (
  `unit_mix_id` uuid,
  `rent_comp_id` uuid,
  `unit_category` text,
  `unit_type` text,
  `unit_count` integer,
  `vacant_units` integer,
  `unit_sf` numeric,
  `unit_floor` character varying(255),
  `no_of_rooms` integer,
  `no_of_bedrooms` integer,
  `no_of_baths` integer,
  `no_of_beds` integer,
  `rent_per_mo` numeric,
  `annual_rent_per_sf` numeric,
  `rent_per_sf_per_mo` numeric,
  `market_rent_per_mo` numeric,
  `market_rent_per_sf` numeric,
  `daily_rate_per_unit` numeric,
  `size_sq_meters` numeric,
  `rent_per_sq_meter` numeric,
  `last_rent_increase` character varying(255),
  `rent_increase_percent` numeric,
  `lease_start_date` character varying(255),
  `lease_expiration_date` character varying(255),
  `community_fee_min` numeric,
  `community_fee_max` numeric,
  `sf_size_min` numeric,
  `sf_size_max` numeric,
  `daily_rate_per_unit_min` numeric,
  `daily_rate_per_unit_max` numeric,
  `entry_fee_min` numeric,
  `entry_fee_max` numeric,
  `contract_rent_min` numeric,
  `contract_rent_max` numeric,
  `market_rent_min` numeric,
  `market_rent_max` numeric,
  `unit_height_ft` numeric,
  `unit_width_ft` numeric,
  `unit_depth_ft` numeric,
  `income_target_percent` numeric,
  `max_gross_lihtc_restricted_rent` numeric,
  `is_lihtc` boolean,
  `utility_allowance` numeric,
  `occupancy_type` text,
  `affordability_status` text,
  `tenant_profile` text,
  `monthly_or_daily_rent` text,
  `custom_fields` jsonb,
  `created_at` timestamp with time zone,
  `updated_at` timestamp with time zone,
  `created_by_user_id` uuid,
  `updated_by_user_id` uuid,
  PRIMARY KEY (`unit_mix_id`),
  FOREIGN KEY (`rent_comp_id`)
      REFERENCES `pva-mvp-wip-v2.rent_comp`(`rent_comp_id`)
);

CREATE TABLE `pva-mvp-wip-v2.property_source_attribution` (
  `attribution_id` uuid,
  `property_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `Property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip-v2.property_merge_audit_log` (
  `audit_log_id` uuid,
  `property_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`),
  FOREIGN KEY (`property_id`)
      REFERENCES `Property`(`property_id`)
);

CREATE TABLE `pva-mvp-wip-v2.sale_comp_merge_audit_log` (
  `audit_log_id` uuid,
  `sale_comp_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`),
  FOREIGN KEY (`sale_comp_id`)
      REFERENCES `pva-mvp-wip-v2.sale_comp`(`sale_comp_id`)
);

CREATE TABLE `pva-mvp-wip-v2.sale_comp_source_attribution` (
  `attribution_id` uuid,
  `sale_comp_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`sale_comp_id`)
      REFERENCES `pva-mvp-wip-v2.sale_comp`(`sale_comp_id`)
);

CREATE TABLE `pva-mvp-wip-v2.lease_comp_merge_audit_log` (
  `audit_log_id` uuid,
  `lease_comp_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`),
  FOREIGN KEY (`lease_comp_id`)
      REFERENCES `pva-mvp-wip-v2.lease_comp`(`lease_comp_id`)
);

CREATE TABLE `pva-mvp-wip-v2.lease_comp_source_attribution` (
  `attribution_id` uuid,
  `lease_comp_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  `created_at` timestamp with time zone,
  `updated_at` timestamp with time zone,
  `created_by_user_id` uuid,
  `updated_by_user_id` uuid,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`lease_comp_id`)
      REFERENCES `pva-mvp-wip-v2.lease_comp`(`lease_comp_id`)
);

CREATE TABLE `pva-mvp-wip-v2.rent_comp_merge_audit_log` (
  `audit_log_id` uuid,
  `rent_comp_id` uuid,
  `field_changed` character varying(100),
  `old_value` text,
  `new_value` text,
  `merged_by_user_or_system` character varying(100),
  `merge_timestamp` timestamp with time zone,
  PRIMARY KEY (`audit_log_id`),
  FOREIGN KEY (`rent_comp_id`)
      REFERENCES `pva-mvp-wip-v2.rent_comp`(`rent_comp_id`)
);

CREATE TABLE `pva-mvp-wip-v2.rent_comp_source_attribution` (
  `attribution_id` uuid,
  `rent_comp_id` uuid,
  `field_name` character varying(100),
  `field_value` text,
  `source_system` character varying(50),
  `ingestion_timestamp` timestamp with time zone,
  `created_at` timestamp with time zone,
  `updated_at` timestamp with time zone,
  `created_by_user_id` uuid,
  `updated_by_user_id` uuid,
  PRIMARY KEY (`attribution_id`),
  FOREIGN KEY (`rent_comp_id`)
      REFERENCES `pva-mvp-wip-v2.rent_comp`(`rent_comp_id`)
);
